### ISSUE TITLE
Create status file on game startup

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#136]

**Comment by garrettmiller** [comment]
As it turns out, writing both a timestamp and a struct to a file in a way that's readable is a bit trickier than anticipated.  Still working on this one.

**Comment by dsantorojr** [comment]
@garrettmiller fmt.Sprintf("%v", struct) should make that struct a string pretty nicely, if that's helpful. I don't know bout time stamps off the top of my head.

I imagine maybe you want something a little more delimited than this, but sprintf in general might get you there.

**Comment by garrettmiller** [comment]
I think that will be difficult to parse... trying to do it with gob encoding right now.

**Comment by dsantorojr** [comment]
if you did something like `sprintf("%v%s%v%s%v...", struct.field1, DELIMITER, struct.field, DELIMITER...)` you'd have defined delimiters. 

Gob encoding might be the way to go (no pun intended). but with the deadline looming, just wanted to get extra ideas out there in case we get stuck and need to brute force it

**Comment by garrettmiller** [comment]
Sure thing, I hear you. Much appreciated.

**Comment by garrettmiller** [comment]
Right now just trying to get nodes reading/writing from file, i'll worry about separating the timestamp thing after that.
