### ISSUE TITLE
Create a plan for demo with Nace

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#169]
Detail plan of where we are going to start, what we're going to say, and how we are going to demo things.

**Comment by garrettmiller** [comment]
@arminm - can you make it?  I believe @helunwencser is unavailable.  I know it's early.

**Comment by arminm** [comment]
@garrettmiller I'll be there guys. Won't leave you alone on the fun. 😉

**Comment by dsantorojr** [comment]
Done.
