### ISSUE TITLE
Boostrap server initial work / update

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#21]
@garrettmiller will take point, @arminm will assist

**Comment by garrettmiller** [comment]
Getting a good start on this, I think there can be a lot of function reuse between Multegula/Messagepasser and Bootstrap.  Also added a run_bootstrap.sh script and have it loaded on our server.

Forgive me, I already forgot - who else was going to work on this once Multicast was finished - @arminm?

**Comment by garrettmiller** [comment]
Bootstrap server runs, and informs clients when it has four nodes to play with.  Seems to work well.  Many thanks to @arminm for his help on this who really got me un-stuck.

Future steps are to:
- Add a timeout (say, 60 seconds) if 4 clients don't join in 60 seconds
- Enforce clients introducing themselves (it currently doesn't do this, see example below)
- Close these connections gracefully, this currently has issues.  Actually it might not be a problem to let them die naturally.
- Add the other side in multegula.go

```
garrett@ubuntu:~$ nc localhost 55555  
MULTEGULA_BOOTSTRAP_SERVER  
CLIENT_INTRODUCE_YOURSELF_NOW  
PLAYER_LIST_BEGIN  
127.0.0.1:43470  
127.0.0.1:43472  
127.0.0.1:43474  
127.0.0.1:43476  
PLAYER_LIST_END
```

**Comment by garrettmiller** [comment]
Current Status:  grouping, timeouts, introduction enforcement, connection closing works.

Remaining issues: 
- Add the other side in multegula.go.  Closing this issue.
