### ISSUE TITLE
Multegula must inform UI of the players in the game

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#29]
This requires a new message type and payload.

**Comment by garrettmiller** [comment]
This will probably come from Bootstrap Server, right?

**Comment by dsantorojr** [comment]
The information will come from the bootstrap server for sure. Multegula will need to forward it on to the UI so that the UI can create players to render appropriately. What I'm talking about here is the Multegula to UI communication so I can make those players.

**Comment by dsantorojr** [comment]
Redundant.
