### ISSUE TITLE
UI to incorporate new screen while multiplayer game is being created

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#32]
Once a user selects "Join Game", Multegula should be informed and attempt to join a game.

**Comment by garrettmiller** [comment]
Do you want a few new message types from Bootstrap Server - "COUNTDOWN_TIME_30" and "CURRENT_PLAYERS_3" for UI information display?

**Comment by dsantorojr** [comment]
@garrettmiller totally never saw this comment. I think those would be awesome...Call it a nice to have

**Comment by garrettmiller** [comment]
Yeah, definitely in "nice to have" category... maybe for now it should say "Waiting up to 30 seconds for players to join...."?

**Comment by dsantorojr** [comment]
Did you see my MovingPaddlesTakingNames.mov? Let me know what you think about that.

**Comment by garrettmiller** [comment]
Looking now.

DUUUUUUUUUUUUUUUUUUUUUUUDE

Edit: **DUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUDE**

**Comment by dsantorojr** [comment]
Ain't she beautiful?

**Comment by garrettmiller** [comment]
It's perfect.
