### ISSUE TITLE
Multegula.go must properly connect to and communicate with Bootstrap server.

### ISSUE THREAD

**Issue by garrettmiller** [arminm/multegula#47]
Multegula must communicate with Bootstrap server, by checking and sending messages in an expected format.

```
garrett@ubuntu:~$ nc localhost 55555
MULTEGULA_BOOTSTRAP_SERVER
CLIENT_SAY_HELLO_NOW
<client says> MULTEGULA_CLIENT_HELLO
WELCOME_CLIENT
PLAYER_LIST_BEGIN
127.0.0.1:43470
127.0.0.1:43472
127.0.0.1:43474
127.0.0.1:43476
PLAYER_LIST_END
```

Considering a specification change - Clients don’t need to introduce themselves by name to the Bootstrap server, they should just confirm that they are in fact a Multegula client
Bootstrap doesn’t care what their name is, just the IP.  The other nodes do, so I imagine that will come in the initial handshaking.

Any thoughts on that?

**Comment by garrettmiller** [comment]
Request @arminm assistance on this one.

**Comment by arminm** [comment]
#56
