### ISSUE TITLE
Update messages to send smaller values

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#59]
There is no need to send "MSG_PADDLE_POS" when we could send "MPP" - Therefore, the messages should be updated to be much shorter with minimal work.

**Comment by garrettmiller** [comment]
Sounds like a good idea.  But we should clearly define what these abbreviations are in comments somewhere.

**Comment by garrettmiller** [comment]
**ACTUALLY** why not make them string variable names, and the actual data sent is the abbreviated version?

**Comment by dsantorojr** [comment]
@garrettmiller check the last commit on the UI branch and what the constants defined in MessageTypes.go look like. (Watch out, when you guys are looking...I might just change them to single byte values :p )

**Comment by dsantorojr** [comment]
*aren't (no editing on the phone...)

**Comment by garrettmiller** [comment]
Looking good!

On Sun, Apr 17, 2016 at 4:58 PM, Daniel Santoro notifications@github.com
wrote:

> *aren't (no editing on the phone...)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/arminm/multegula/issues/59#issuecomment-211116225

## 

_Garrett M. Miller_
MSIS Class of 2016
Information Networking Institute
Carnegie Mellon University
(814) 573-6481 | @GarrettMMiller https://twitter.com/GarrettMMiller

**Comment by dsantorojr** [comment]
All standard payloads (e.g. LEFT, RIGHT, etc) have been reduced to one letter

**Comment by dsantorojr** [comment]
All message types (e.g. MSG_PADDLE_POS, MSG_BLOCK_BROKEN) have been reduced to three letters

**Comment by dsantorojr** [comment]
All floating point numbers have been reduced to base 10 fixed point
