### ISSUE TITLE
Create .mlev (Multegula Level) files for 5 different levels

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#74]
Files with a special extension `.mlev` that define the levels in a game. This can can take the place of the unicorn informing everyone of the current level configuration (where all the blocks are and what is their power-up status) at the beginning of each level, which would be a nice to have.

In this way, every client has the level configurations, complete with power-ups, locally. During rejoin, the unicorn just needs to inform the rejoining player of which blocks are active, instead of, again, all the configuration information.

Every block has four parameters: `xCenter`, `yCenter`, `PowerUp`, and the `tilt` (vertical or horizontal). These should all be defined in the file. The index identifier of a block can be inferred from the order of the file.

Node, that instead of defining the exact `xCenter` and `yCenter`, it might be good to work similarly to what the current `__init__` function of `Levels.py` does. So, instead of saving the exact `xCenter` and `yCenter`, you'll save a multiplier for a constant, say `1`, or `2` that will be multiplied by `X_THIRD` or `Y_THIRD` when the level is actually created.

**Comment by dsantorojr** [comment]
You can change the extension, that's obviously not important. I just thought it'd be cool to have our own extension.

**Comment by garrettmiller** [comment]
.mlev is good :)

**Comment by garrettmiller** [comment]
Files are written, again, are Python code right now, and 4-10 are empty.  Thinking of the best way to do this.

**Comment by dsantorojr** [comment]
Changed requirement to 5 different levels

**Comment by garrettmiller** [comment]
1-3 are done thus far.  Placeholders in for 4 and 5.

**Comment by garrettmiller** [comment]
Switched to three levels.  Closing issue.
