### ISSUE TITLE
Update Level.py with readLevel method

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#75]
I imagine that instead of the **init** of Level.py creating the levels, it will instead use the `glob` library in python to look for all `.mlev` files, parse them with a `readLevel` method and then store them in the `self.levels` array as it does now.

This ticket is for creating the `readLevel` method. As noted in #74, this may need to do some multiplication math to get the right `xCenter` and `yCenter` for the blocks.

**Comment by garrettmiller** [comment]
Currently reading in Python code, not a "cleaner" way.  Currently thinking about the best way to do this.

**Comment by garrettmiller** [comment]
Closing this, since levels will be reduced to 5, and remain as Python code, readLevel method exists.
