### ISSUE TITLE
Update Level.py to read in levels

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#76]
I imagine that instead of the init of `Level.py` creating the levels, it will instead use the glob library in python to look for all `.mlev` files, parse them with a `readLevel` method and then store them in the `self.levels` array as it does now.

This ticket is for the `__init__` function work of `Level.py`

**Comment by garrettmiller** [comment]
Init calls readLevel, which are currently Python code snippets, but since this is just init, we can work with this.
