### ISSUE TITLE
Color blocks based on Power up

### ISSUE THREAD

**Issue by dsantorojr** [arminm/multegula#78]
See TODO comment in `Block.py`and power up definitions in `typedefs.py`

**Comment by garrettmiller** [comment]
Is every block going to have a powerup, or only some?  I think only some makes more sense.

Also, what is the criticality of this feature?  If powerups can be implemented as a "nice-to-have", I think that would be fine.

**Comment by garrettmiller** [comment]
**UPDATE:**  Colors of blocks will be randomly determined.  Powerups have been relegated to "nice to have" status.

**Comment by dsantorojr** [comment]
Oops, sorry. Didn't mean to close.
