### ISSUE TITLE
Make Multegula Big Again

### ISSUE THREAD

**Issue by garrettmiller** [arminm/multegula#93]
Make Multegula window big again for video/demo purposes :)  Probably an easy fix, I just don't want to touch the wrong thing.  Tagging @dansantorojr for this one since it's probably easiest for him to fix.

**Comment by dsantorojr** [comment]
Oh yeah, this is simple. It's in typedefs.py. `CANVAS_WIDTH` and `CANVAS_HEIGHT` set literally everything in the game. `700` is what we'll ship with.

**Comment by dsantorojr** [comment]
#187
