### ISSUE TITLE
Level Order appears to go 3, 1, 2?

### ISSUE THREAD

**Issue by garrettmiller** [arminm/multegula#94]
For some reason, levels on my machine run in the order 3, 1, 2.  They're numbered correctly, these are just the brick layouts. No idea why.

**Comment by dsantorojr** [comment]
I am not seeing this. Is this still an issue?

**Comment by garrettmiller** [comment]
Yes, this is what I get for Level 1:

![image](https://cloud.githubusercontent.com/assets/2850784/14727941/38ae27f4-07fe-11e6-95fc-85b7af36995f.png)

**Comment by dsantorojr** [comment]
Could it be the way that glob reads on other operating systems?

**Comment by garrettmiller** [comment]
Let me see if the issue persists on my macbook as well as linux VM.

**Comment by garrettmiller** [comment]
I can't reproduce this on my Macbook, it behaves as expected.  I will investigate further on Linux tonight.

**Comment by dsantorojr** [comment]
Thinking about fixing this by having the unicorn send out the current level before the game starts. I'm going to add it as a field in the MSG_PAUSE_UPDATE so there are three chances for a player to get the message. Think that'll fix the issue?

**Comment by dsantorojr** [comment]
I guess my other question is this...did the game SAY it was level three, or just produce level 3 and call it level 1? I hope it is the latter, because then we're dealing with the order in which glob opens the files, not something way worse.

**Comment by garrettmiller** [comment]
no, it said Level 1, it just issued the 3rd block layout.

I can reproduce this on my Linux VM at home, my Macbook behaves as expected.  I will spin up a brand-new Linux VM and test.

**Comment by garrettmiller** [comment]
Confirmed.  I’ll look into this issue closer but it behaves that way on a fresh installation on a fresh Kali Linux VM (so a completely different distro, too)

**Comment by garrettmiller** [comment]
Globs must behave differently on OSX versus Linux.  Fixed it by wrapping the glob in a `sorted()`
